# Homework Assignment #1

### Due Date: Tuesday, November 26, by Midnight

### Instructions
For each question, show all your work and explain each step where possible. This assignment covers calculus, linear algebra, and probability theory. Some questions may require combining concepts from multiple sections, so ensure you review all material thoroughly. Good luck!

**Note:** For all probability questions, use exact values when possible, and round your final answers to four decimal places if needed. For calculus and linear algebra questions, include clear explanations for each step of your work.

## Part I: Calculus (Derivatives and Integrals)

### Question 1
Let $ f(x) = x^3 - 6x^2 + 9x - 4 $. 
1. Find $ f'(x) $, the first derivative of $ f(x) $.
2. Determine the critical points of $ f(x) $ by solving $ f'(x) = 0 $.
3. Using the second derivative test, classify each critical point as a local maximum, minimum, or point of inflection.

-- Your Answer Here --

Response: 
1. $ f'(x) $  equals to  $ 3x^2 -12x + 9 $.
2. So according to the equation just above, $ 3x^2 -12x + 9 $ = 0, then $ 3 (x - 3) (x - 1) = 0 $, the cirtical points are 3 and 1.
3. so the second derivative equation will $ f''(x) = 6 x -12 $, so when $ x = 1 $, the equation is -6, while $ x = 3 $, the equation is 6, so the $ x=1 $ is the local maximum, and $ x = 3 $ is lcoal minimum

### Question 2
Evaluate the following indefinite integral:

$$
\int \frac{2x^3 - 5x + 3}{x^2} \, dx
$$

-- Your Answer Here --

Response: 

Question 2
Evaluate the following indefinite integral:

$$
\int \frac{2x^3 - 5x + 3}{x^2} \, dx =  \int \frac{2x^3}{x^2} \, dx +  \int \frac{- 5x }{x^2} \, dx + \int \frac{3}{x^2} \, dx = \int 2x dx +  \int \frac{- 5}{x} \, dx  + 3 \frac{x^{-1}}{-1} \ = x^2 -5 \ln x - \frac{3}{x} + constant
$$

### Question 3
Compute the definite integral:

$$
\int_0^3 (3x^2 - 4x + 2) \, dx
$$

Then interpret the result as the area under the curve of $ f(x) = 3x^2 - 4x + 2 $ over the interval $ [0, 3] $.

-- Your Answer Here --

$$
\int_0^3 (3x^2 - 4x + 2) \, dx = \int_0^3 3x^2 \, dx - 4\int_0^3 x \, dx + \int_0^3 2 \, dx = [x^3 - 2x^2 + 2x]_0^3 = 3^3 - 2*9 + 6 - 0 + 0 - 0 = 27 - 18 + 6 = 15
$$

### Question 4
Let $ g(x) = x e^x $.
1. Find $ g'(x) $ using the product rule.
2. Determine the integral $ \int x e^x \, dx $ by using integration by parts.

-- Your Answer Here --

Response:

1. $ g'(x) = 1e^x + xe^x $


2. We need integration by parts formula here:


$ \int x e^x dx = xe^x - \int e^x  dx = xe^x - e^x + constant $




### Question 5
Suppose $ h(x) = \sin(x) e^{3x} $.
1. Calculate $ h'(x) $.
2. Compute $ \int \sin(x) e^{3x} \, dx $ using integration by parts twice.

-- Your Answer Here --

Response: 

1. $ h' (x) = \cos(x) e^{3x} + 3 \sin(x)e^{3x} $

2. We need integration by parts formula here also well. So  

$$
\int \sin(x) e^{3x} \, dx  = sin(x) (e^{3x} dx) - \int \frac{1}{3} e^{3x}\cos(x)dx = \frac{1}{3} \sin(x) e^{3x} - \frac{1}{3}\int \cos(x) e^{3x} dx = \frac{1}{3} \sin(x) e^{3x}  - \frac{1}{3} (\frac{1}{3}\cos(x)e^{3x} + \frac{1}{3}\int \sin(x)e^{3x}dx)
$$



So move the two items with same of the $\int \sin(x)e^{3x}dx$ together on the left:


$$
\int \sin(x)e^{3x}dx (1 + \frac{1}{9}) = \frac{1}{3} \sin(x) e^{3x}  - \frac{1}{9} \cos(x)e^{3x}
$$



So

$$
\int \sin(x)e^{3x}dx = \frac{3}{10} \sin(x)e^{3x} - \frac{1}{10} cos(x)e^{3x} + constant
$$










## Part II: Linear Algebra

### Question 6
Consider the following system of linear equations:
$$
2x + 3y - z = 4
$$
$$
x - 2y + 4z = -3
$$
$$
3x + y + 2z = 5
$$
1. Write the system in matrix form $ AX = B $.
2. Find the determinant of $ A $.
3. If the determinant is non-zero, use the inverse of $ A $ to solve for $ X $.

-- Your Answer Here --

Response:

1. 

$$
A = \begin{pmatrix} 2 & 3 & -1 \\ 1 & -2 & 4 \\ 3 & 1 & 2 \end{pmatrix} , 

X = \begin{pmatrix} x \\ y \\ z \end{pmatrix}, \quad and \quad 

B = \begin{pmatrix} 4 \\ -3 \\ 5 \end{pmatrix}
$$



2. 

$$

det(A) = 2 * det(
    \begin{bmatrix}
    -2 & 4 \\
    1 & 2
    \end{bmatrix}
) - 3 * det(
    \begin{bmatrix}
    1 & 4 \\
    3 & 2
    \end{bmatrix}
) - 1 * det(
    \begin{bmatrix}
    1 & -2 \\
    3 & 1
    \end{bmatrix}
) = 2*(-8) - 3*(-10) - 1*(7) = -16 + 30 - 7 = 7

$$



3. 
As above, the determinant is 7 (not 0), according to the equation: 
$ X = A^{-1} * B $









In [1]:
import numpy as np

A = np.array([[2, 3, -1],
              [1, -2, 4],
              [3, 1, 2]])
A_inverse = np.linalg.inv(A) # Inverse of A

B = np.array([4, -3, 5])


X = np.dot(A_inverse, B)
print('X: ', X)

X:  [ 5.57142857 -3.71428571 -4.        ]


### Question 7
Given the matrices:

$$
A = \begin{pmatrix} 2 & -1 \\ 0 & 3 \end{pmatrix} \quad \text{and} \quad B = \begin{pmatrix} 4 & 1 \\ -2 & 5 \end{pmatrix}
$$

1. Compute $ A + B $ and $ A - B $.
2. Find the product $ AB $ and $ BA $.
3. Is $ AB = BA $? Justify your answer.

-- Your Answer Here --

In [3]:
import numpy as np

A = np.array([[2,  -1],[0, 3]])
B = np.array([[4,  1],[-2, 5]])

# 1. A+ B and A-B
print('A + B: ', np.add(A, B))
print('A - B: ', np.subtract(A, B))


# 2. the product of A and B
print('A * B: ', np.dot(A, B))
print('B * A: ', np.dot(B, A))


A + B:  [[ 6  0]
 [-2  8]]
A - B:  [[-2 -2]
 [ 2 -2]]
A * B:  [[10 -3]
 [-6 15]]
B * A:  [[ 8 -1]
 [-4 17]]


3. No, they are not the same

### Question 8
Let $ C $ be a $ 3 \times 3 $ matrix:

$$
C = \begin{pmatrix} 1 & 2 & 3 \\ 0 & -1 & 4 \\ 2 & 1 & 0 \end{pmatrix}
$$

1. Find the transpose of $ C $, denoted $ C^T $.
2. Calculate $ C + C^T $.
3. Determine if $ C + C^T $ is symmetric.

-- Your Answer Here --

In [6]:
C = np.array([[1, 2, 3],
              [0, -1, 4],
              [2, 1, 0]])


# 1. transpose of C
print('1. Transpose of C: ', np.transpose(C))

# 2. C + transpose of C
print('2. C + Transpose of C: ', np.add(C, np.transpose(C)))


# 3 symmetric matrix
c_and_c_transpose = np.add(C, np.transpose(C))
c_transpose_and_c = np.add(np.transpose(C), C)

if np.array_equal(c_and_c_transpose, c_transpose_and_c):
    print('3. C is a symmetric matrix')
else:
    print('3. C is not a symmetric matrix')

1. Transpose of C:  [[ 1  0  2]
 [ 2 -1  1]
 [ 3  4  0]]
2. C + Transpose of C:  [[ 2  2  5]
 [ 2 -2  5]
 [ 5  5  0]]
3. C is a symmetric matrix


### Question 9
A matrix $ D $ is defined as:

$$
D = \begin{pmatrix} a & 0 & 0 \\ 0 & b & 0 \\ 0 & 0 & c \end{pmatrix}
$$

1. Describe the type of matrix $ D $ and explain its properties.
2. If $ D $ is a diagonal matrix, find its determinant.
3. Explain the significance of a diagonal matrix in terms of linear transformations.

-- Your Answer Here --

Response:
1. The matrix is diagonal matrix
2. the determinant equals to a*b*c
3. It depends on the a, b and c in different axes, like if a = 2, it scales this first axis by 2, etc

### Question 10
Let $ E $ be a $ 2 \times 2 $ matrix defined as:

$$
E = \begin{pmatrix} 3 & 4 \\ 2 & 1 \end{pmatrix}
$$

1. Find the eigenvalues of $ E $.
2. For each eigenvalue, find the corresponding eigenvector.
3. Explain how the eigenvalues and eigenvectors can be used to understand transformations represented by $ E $.

-- Your Answer Here --

In [7]:
# 1 eign  value for E
E = np.array([[3, 4],
              [2, 1]])

eigen_values, eigen_vectors = np.linalg.eig(E)
print('1. Eigen values: ', eigen_values)

# find the corresponding eigen vectors
print('2. Eigen vectors: ', eigen_vectors)

1. Eigen values:  [ 5. -1.]
2. Eigen vectors:  [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


3. So according to the result above, it have two eigen values of 5 and -1, so it scales the axes by 5 and -1 separately

## Part III: Probability Theory

### Question 11
In a population, 30% of individuals have a specific genetic marker. A test for this marker has a 95% accuracy rate for individuals with the marker and an 80% accuracy rate for those without the marker.
1. Define the events and write out the given probabilities.
2. Using Bayes' theorem, calculate the probability that an individual actually has the marker given a positive test result.

-- Your Answer Here --

Response:
$ p(genetic) = 0.3 $

$ p(x) =0.95 $

1. There are two possibles: true positive, and ture negative
true positive: $ p(x|genetic) = 0.95 $
ture negative: $ p(x^{'}|genetic^{'}) = 0.8 $


2. According to the Bayes's equation:
$ p(genetic|x) = \frac{p(x|genetic) * p(genetic)} {p(x)} $


$ p(x) = p(x|genetic)*p(genetic) + (1- p(x^{'}|genetic^{'}))*(1-p(genetic)) = 0.95*0.3 + 0.2*0.7 =0.425 $
p(genetic|x) = 0.95*0.3/0.425




In [8]:
print("2. result: ", 0.95*0.3/0.425)

2. result:  0.6705882352941176


### Question 12
A die is rolled 12 times. Let $ X $ be the random variable representing the number of times a "5" appears.
1. What type of probability distribution does $ X $ follow?
2. Calculate the probability that "5" appears exactly 4 times.
3. Determine the expected number of times "5" will appear in 12 rolls.

-- Your Answer Here --

In [10]:
# 1. it follows bionomial distribution

# Probability of "5" appears  4 times
n = 12
p = 1/6
n4 = 4

# calculate (n, n4) * p^n4 * (1-p)^(n-n4)
from math import factorial
from math import pow
p4 = factorial(n)/(factorial(n4)*factorial(n-n4)) * pow(p, n4) * pow(1-p, n-n4)
print('2. Probability of "5" appears 4 times: ', p4)



# the expected number of "5" appears from 12 rolls
n = 12
p = 1/6
expected_value = n * p
print('3. Expected number of "5" appears from 12 rolls: ', expected_value)

2. Probability of "5" appears 4 times:  0.08882807058941516
3. Expected number of "5" appears from 12 rolls:  2.0


### Question 13
A bookstore averages 3 customer visits per hour. Assume the number of customer visits per hour follows a Poisson distribution.
1. Calculate the probability that exactly 5 customers visit in a given hour.
2. Find the probability that at least 1 customer visits in a given hour.

-- Your Answer Here --

Response:
So the $ \lambda = 3 $ according the question


In [12]:

Lambda = 3
k = 5
from math import exp
from math import factorial
p = exp(-Lambda) * pow(Lambda, k) / factorial(k)
print('1. Probability of 5 customers arrive in 1 hour: ', p)


# Find the probability that at least 1 customer visits in a given hour.
p = 1 - exp(-Lambda)
print('2. Probability that at least 1 customer visits in a given hour: ', p)





1. Probability of 5 customers arrive in 1 hour:  0.10081881344492448
2. Probability that at least 1 customer visits in a given hour:  0.950212931632136


### Question 14
Assume a continuous random variable $ Y $ follows a normal distribution with mean $ \mu = 50 $ and standard deviation $ \sigma = 5 $.
1. Calculate the probability that $ Y $ takes a value between 45 and 55.
2. Find the value $ y $ such that $ P(Y \leq y) = 0.85 $.

-- Your Answer Here --

In [14]:

# 1. the probability that Y takes a value between 45 and 55.
from scipy.stats import norm
mu = 50
sigma = 5
p = norm.cdf(55, mu, sigma) - norm.cdf(45, mu, sigma)
print('1. Probability that Y takes a value between 45 and 55: ', p)


# Find the value y such that P(Y <= y) = 0.85
y = norm.ppf(0.85, mu, sigma)
print('2. Value y such that P(Y <= y) = 0.85: ', y)

1. Probability that Y takes a value between 45 and 55:  0.6826894921370859
2. Value y such that P(Y <= y) = 0.85:  55.18216694746895


### Question 15
A company's product quality control process involves two independent tests. Each test has a 98% probability of detecting a defect if it is present.
1. What is the probability that both tests detect a defect when it is present?
2. What is the probability that at least one test detects a defect when it is present?
3. If the company requires both tests to detect a defect before rejecting a product, calculate the probability that a defective product will be rejected.

-- Your Answer Here --

In [18]:

# 1.
p =0.98
p_both = p*p 
print('1. Probability both: ', p_both)


# 2.
p_at_least_one = 1 - (1-p)*(1-p)
print('2. Probability at least one: ', p_at_least_one)



# 3. 
p_reject = p_both
print('3. Probability of reject: ', p_reject)



1. Probability both:  0.9603999999999999
2. Probability at least one:  0.9996
3. Probability of reject:  0.9603999999999999
